Cleaned up leader footstep ui in 'Member List' tile
DiscipleTools/disciple-tools-theme pull request #1636
Opened 2022-04-27 20:10 UTC by prykon

Responds to: #1398 

**Current behavior:**
- Black Footstep icon removed for leaders
- Leader toggle footstep icon is now black if member is leader

<img width="400" src="https://user-images.githubusercontent.com/36511666/165622636-e3743d67-037f-4c85-b0d6-acf389ebbe94.png">

2022-04-28 09:30 UTC, corsacca commented
Awesome work @prykon!

![leader](https://user-images.githubusercontent.com/24901539/165722532-a4c8efbd-c903-4a6a-b894-68ff7043cc30.gif)
The in between state is a bit confusing. 
@prykon what do you think of this idea?
When the foot is clicked: transform the icon into the loading circle. When the API call comes back, show the correct foot.

2022-04-28 11:48 UTC, prykon commented
> Awesome work @prykon!
> 
> ![leader](https://user-images.githubusercontent.com/24901539/165722532-a4c8efbd-c903-4a6a-b894-68ff7043cc30.gif) The in between state is a bit confusing. @prykon what do you think of this idea? When the foot is clicked: transform the icon into the loading circle. When the API call comes back, show the correct foot.

Sounds good! I'm on it...

2022-04-28 19:46 UTC, prykon commented
The spinner appears when you make a member a leader. When you remove leadership, the row disappears before the spinner can be shown.

(screenshot frame rate slower than reality)

<img width="400" src="https://user-images.githubusercontent.com/36511666/165833191-590b2033-c3d5-4989-8f1f-667120417443.gif">

2022-04-29 13:46 UTC, corsacca requested changes

2022-04-29 13:46 UTC, corsacca commented on dt-groups/groups.js
>        existingLeaderIcon.remove()
@prykon  Remove `existingLeaderIcon.remove()` and the spinner will work both ways:

2022-04-29 13:46 UTC, corsacca commented on dt-groups/groups.js
> +    let spinner = `<img src="/wp-content/themes/disciple-tools-theme/dt-core/admin/img/spinner.svg" width="15px">`
use this format: `<img src="${template_dir}/dt-assets/images/chevron_up.svg"/>`

2022-04-29 13:46 UTC, corsacca commented on dt-groups/groups.js
> +    let spinner = `<img src="/wp-content/themes/disciple-tools-theme/dt-core/admin/img/spinner.svg" width="15px">`
spinner.svg is in the theme root.

2022-05-02 17:02 UTC, corsacca commented
Very nice!

2022-05-02 17:02 UTC, merged