Customization (DT) Beta - Font Icon Picker
DiscipleTools/disciple-tools-theme pull request #2078
Opened 2023-05-23 15:31 UTC by kodinkat

![Screenshot 2023-05-23 at 16 25 40](https://github.com/DiscipleTools/disciple-tools-theme/assets/19330800/584c38c8-2bed-4a2c-add5-583b9db484c1)

2023-05-23 17:14 UTC, prykon commented
Tile Preview doesn't update on new field creation, but this issue appears to exist from before this branch.

Aside from my previous comment, no errors were found. Functionality works.

Nice job, @kodinkat !

2023-05-23 17:15 UTC, prykon requested changes
@kodinkat Thanks so much for coding this! I'm testing it as we speak.

In order to keep the UI consistent, could you...?

- [ ] Make the edit field settings modal card flip and make the icon selector modal unflip
- [ ] Add the `dt-admin-modal-overlay` class when opening the icons modal

Thanks again!

2023-05-24 15:34 UTC, kodinkat commented
> @kodinkat Thanks so much for coding this! I'm testing it as we speak.
> 
> In order to keep the UI consistent, could you...?
> 
> * [ ]  Make the edit field settings modal card flip and make the icon selector modal unflip
> * [ ]  Add the `dt-admin-modal-overlay` class when opening the icons modal
> 
> Thanks again!

@prykon That's now in for you... Updating font icon picker dialog to adopt flip animation turned out to be slightly fiddlier then anticipated; so let me know if anything...

2023-05-26 13:14 UTC, prykon approved these changes

2023-05-26 13:16 UTC, prykon commented
@kodinkat I would add a `margin: 1.5em` to the `.ui-dialog-buttonset`
Aside from that, everything looks good!

2023-05-31 13:24 UTC, prykon commented
I think we're good to merge, @corsacca

2023-06-05 10:25 UTC, kodinkat commented
@prykon @corsacca - See if recent updates now address multi-select mdi icon preview issues.

2023-06-05 13:42 UTC, prykon commented
@kodinkat Icon updates properly on the admin page and dt frontend but not if it's inside a multi select...

**This is ok**
![Screenshot 2023-06-05 at 10 40 39](https://github.com/DiscipleTools/disciple-tools-theme/assets/36511666/c7223e21-6b8a-419a-adca-3eac30391733)

**This is broken**
![Screenshot 2023-06-05 at 10 42 04](https://github.com/DiscipleTools/disciple-tools-theme/assets/36511666/306da581-039f-4a6c-b040-71abe65a5c6a)

2023-06-05 15:43 UTC, kodinkat commented
@prykon try it now and let me know.. :)

2023-06-06 06:19 UTC, corsacca commented
@prykon, That looks like an issue with the Church Health and not with the implementation of the font icon picker. Maybe a separate issue?

2023-06-06 06:29 UTC, corsacca commented on dt-core/global-functions.php
> +                // Determine icon html element shape to be adopted.
@kodinkat, font icons need to use the `font-icon` field, not the `icon` field, then the code at line 340 works

2023-06-06 11:50 UTC, kodinkat commented
@prykon @corsacca give it a try now and let me know how things hold up, especially on the group church health side of things! :)

2023-06-06 12:21 UTC, prykon commented
@kodinkat Looks good now!

2023-06-07 09:42 UTC, kodinkat commented
> @kodinkat @prykon looking good guys. @kodinkat i tried adding a new field and got: <img alt="image" width="603" src="https://user-images.githubusercontent.com/24901539/243739799-eb839db7-e722-4e3f-b131-35951dfb8824.png"> There is a trim() error, but then show:
> 
> this is what a new field (multi_select) looks like: <img alt="image" width="587" src="https://user-images.githubusercontent.com/24901539/243739487-105f3e65-a138-4663-9837-b34ee0dd2b76.png">

@corsacca sanity checked new field / option flows and both held true for me. @prykon does it hold true for you?

![Screenshot 2023-06-07 at 10 20 05](https://github.com/DiscipleTools/disciple-tools-theme/assets/19330800/96f92fff-177c-4b83-a394-258841413f51)

![Screenshot 2023-06-07 at 10 20 56](https://github.com/DiscipleTools/disciple-tools-theme/assets/19330800/c436e9c8-e005-4ab7-b3fb-e80914ee4446)

![Screenshot 2023-06-07 at 10 24 09](https://github.com/DiscipleTools/disciple-tools-theme/assets/19330800/5a5e84ef-9480-4d60-86fd-9bfcfe157568)

![Screenshot 2023-06-07 at 10 25 38](https://github.com/DiscipleTools/disciple-tools-theme/assets/19330800/f2e6a3ed-9650-4c92-8f22-7c784d860cfa)

![Screenshot 2023-06-07 at 10 27 17](https://github.com/DiscipleTools/disciple-tools-theme/assets/19330800/711e3df9-eaab-45a4-a450-71794e8e9e59)

2023-06-07 12:53 UTC, prykon commented
@kodinkat Thanks for hanging in there for this one; so many ins and outs!

I found a bug...
<img width="495" alt="Screenshot 2023-06-07 at 09 50 45" src="https://github.com/DiscipleTools/disciple-tools-theme/assets/36511666/3630cbd9-7c3b-477f-8975-6e0b5e8f5ded">

**Steps to reproduce:**

1. Create a new field
2. Click to edit the field (no icon image is shown, but this might be out of scope)
3. Edit the field name only (don't change icon settings)
4. Re-click to edit the field (icon image now appears but is broken).

2023-06-08 10:13 UTC, kodinkat commented
> @kodinkat Thanks for hanging in there for this one; so many ins and outs!
> 
> I found a bug... <img alt="Screenshot 2023-06-07 at 09 50 45" width="495" src="https://user-images.githubusercontent.com/36511666/244064728-3630cbd9-7c3b-477f-8975-6e0b5e8f5ded.png">
> 
> **Steps to reproduce:**
> 
> 1. Create a new field
> 2. Click to edit the field (no icon image is shown, but this might be out of scope)
> 3. Edit the field name only (don't change icon settings)
> 4. Re-click to edit the field (icon image now appears but is broken).
> 
> Apparently, it's saving the icon value to _undefined_ and that also breaks the frontend... <img alt="Screenshot 2023-06-07 at 09 59 40" width="830" src="https://user-images.githubusercontent.com/36511666/244067212-03aae2f3-e3cf-4003-b8af-5faad179646d.png">

@prykon thanks for this and for the steps; which helped me to reproduce! A fix has now been pushed, so feel free to have a play and let me know if there are still any remaining hidden bugs..... :)

2023-06-08 13:34 UTC, prykon commented
@kodinkat
Found a UI thing... the 'Icon' button should not be on a new line.
![Screenshot 2023-06-08 at 10 24 12](https://github.com/DiscipleTools/disciple-tools-theme/assets/36511666/769a8add-7313-41df-8212-3085563076c8)

@corsacca Do we want icons on field options for a dropdown field type?

Everything else looks great!

2023-06-09 12:18 UTC, prykon commented
Looking good, @kodinkat!
I think it's requiring an onclick prevent default or something.

https://github.com/DiscipleTools/disciple-tools-theme/assets/36511666/c8600591-0ca8-4ff5-8e49-a1bd2419dc04

2023-06-09 12:38 UTC, kodinkat commented
> Looking good, @kodinkat! I think it's requiring an onclick prevent default or something.
> 
>  Screen.Recording.2023-06-09.at.09.17.31.mov

@prykon thanks for this... However, issue not showing up on my end for `.change-icon-button` button class types or any other buttons..

Anyway, just to be on the safe-side, I've added `e.preventDefault()` on `.change-icon-button` click events; but not on any others, to avoid disrupting any pre-existing logic..

2023-06-09 12:56 UTC, prykon commented
> > Looking good, @kodinkat! I think it's requiring an onclick prevent default or something.
> > Screen.Recording.2023-06-09.at.09.17.31.mov
> 
> @prykon thanks for this... However, issue not showing up on my end for `.change-icon-button` button class types or any other buttons..
> 
> Anyway, just to be on the safe-side, I've added `e.preventDefault()` on `.change-icon-button` click events; but not on any others, to avoid disrupting any pre-existing logic..

@kodinkat  It's working now! Also, no other bugs found.

@corsacca are we good to push?

2023-06-09 15:16 UTC, merged